Este notebook é basedo no notebook do mrdbourke: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Tensores

### Escalar

In [2]:
escalar = torch.tensor(7)
escalar

tensor(7)

In [3]:
escalar.ndim

0

In [4]:
escalar.item()

7

### Vetor

In [12]:
vetor = torch.tensor([1,7])
vetor , vetor.shape, vetor.ndim

(tensor([1, 7]), torch.Size([2]), 1)

### Matriz

In [38]:
MATRIX = torch.tensor([[3,6], [2,5]])
MATRIX, MATRIX.dim, MATRIX.shape, MATRIX[0], MATRIX[1]

(tensor([[3, 6],
         [2, 5]]),
 <function Tensor.dim>,
 torch.Size([2, 2]),
 tensor([3, 6]),
 tensor([2, 5]))

### Tensor

In [37]:
TENSOR = torch.tensor([[[2,5,7], [2,9,8], [2,3,9]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[2, 5, 7],
          [2, 9, 8],
          [2, 3, 9]]]), 3, torch.Size([1, 3, 3]))

In [21]:
TENSOR[0]

tensor([[2, 5, 7],
        [2, 9, 8],
        [2, 3, 9]])

In [36]:
TENSOR[0,0,1]

tensor(5)

In [41]:
TENSOR.size()

torch.Size([1, 3, 3])

### Tensores Aleatórios

In [42]:
TENSOR_ALEATORIO = torch.rand(3,4)
TENSOR_ALEATORIO

tensor([[0.9005, 0.9319, 0.1600, 0.0708],
        [0.9731, 0.2383, 0.0817, 0.9728],
        [0.4746, 0.6787, 0.3129, 0.6931]])

In [45]:
TENSOR_ALEATORIO.ndim, TENSOR_ALEATORIO.shape

(2, torch.Size([3, 4]))

In [46]:
TENSOR_ALEATORIO[1,:]

tensor([0.9731, 0.2383, 0.0817, 0.9728])

Tensor RGB para imagem

In [48]:
TENSOR_IMAGEM = torch.rand(3,224,224)

In [49]:
TENSOR_IMAGEM.shape, TENSOR_IMAGEM.ndim, TENSOR_IMAGEM

(torch.Size([3, 224, 224]),
 3,
 tensor([[[0.4585, 0.3512, 0.9960,  ..., 0.9635, 0.9038, 0.9350],
          [0.3343, 0.1927, 0.0600,  ..., 0.3554, 0.1525, 0.3498],
          [0.1752, 0.6002, 0.1730,  ..., 0.6876, 0.4311, 0.9638],
          ...,
          [0.6028, 0.3213, 0.7064,  ..., 0.7567, 0.5419, 0.7434],
          [0.0719, 0.8203, 0.3674,  ..., 0.1230, 0.3335, 0.5558],
          [0.1123, 0.1179, 0.3466,  ..., 0.8594, 0.0134, 0.3071]],
 
         [[0.2754, 0.9289, 0.4222,  ..., 0.5473, 0.8465, 0.4881],
          [0.5024, 0.6476, 0.5556,  ..., 0.5372, 0.2269, 0.0850],
          [0.3160, 0.8390, 0.6497,  ..., 0.0089, 0.6369, 0.8192],
          ...,
          [0.0156, 0.9300, 0.1396,  ..., 0.8527, 0.1400, 0.1334],
          [0.7087, 0.9609, 0.5314,  ..., 0.7753, 0.7321, 0.1672],
          [0.9875, 0.4667, 0.2341,  ..., 0.6231, 0.0413, 0.2299]],
 
         [[0.7785, 0.9931, 0.5989,  ..., 0.5722, 0.0146, 0.1616],
          [0.4340, 0.3350, 0.4745,  ..., 0.5503, 0.5429, 0.9251],
        

### Tensores de 0s e 1s

In [52]:
ZEROS = torch.zeros(3,4)
ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
UNS = torch.ones(3,4)
UNS

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Ranges de Tensores

In [58]:
RANGE = torch.arange(1,11)
RANGE

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Tensores Like

In [60]:
DEZ_ZEROS = torch.zeros_like(RANGE)
DEZ_ZEROS

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tipos de Dados

In [63]:
# Float 32

float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=None, # Default float32
                               device=None, # Default "cpu"
                               requires_grad=False) # Default "False"
float_32_tensor.dtype

torch.float32

In [67]:
float_16_tensor = float_32_tensor.to(dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [69]:
print(f"Tipo do tensor: {float_16_tensor.dtype}")
print(f"Tipo do tensor: {float_32_tensor.dtype}")

Tipo do tensor: torch.float16
Tipo do tensor: torch.float32


### Operações com Tensores

* Soma
* Subtração
* Multiplicação (por elemento)
* Divisão
* Multiplicação de Matrizes

In [73]:
tensor  = torch.tensor([1,2,3]) + 10
tensor

tensor([11, 12, 13])

In [74]:
tensor * 10


tensor([110, 120, 130])

In [75]:
tensor - 1

tensor([10, 11, 12])

In [81]:
torch.div(tensor,0.5)

tensor([22., 24., 26.])

In [98]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[7,8],[9,10],[11,12]])
t1.shape, t2.shape

torch.matmul(t1, t2) # Funciona 
# torch.matmul(t1, t1) # Não funciona pois as dimensões INTERNAS precisam ser idênticas

tensor([[ 58,  64],
        [139, 154]])

In [107]:
t3 = t1 @ t2 # @ é o perador do matmul e mm é um alias poara matmul
print(f"{t1.shape}")
print(f"{t2.shape}")
print(f"{t3}") # O resultado da multiplicação de matriz, tem o shape das dimensões EXTERNAS.

torch.Size([2, 3])
torch.Size([3, 2])
tensor([[ 58,  64],
        [139, 154]])


In [108]:
#Podemos manipular o shape de um tensor usando o *transpose*
t4 = t1 @ t1.T
t4

tensor([[14, 32],
        [32, 77]])

In [110]:
t1.T.shape

torch.Size([3, 2])

### Min, Max, Media e Soma

In [129]:
x = torch.arange(0,100,step=10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [133]:
x.min()

tensor(0)

In [134]:
x.max()

tensor(90)

In [135]:
#Precisamos ter o tipo de dados float para usar o mean()
x = x.to(dtype=torch.float32)
x.mean()

tensor(45.)

In [136]:
torch.sum(x)

tensor(450.)

### Remodelando, Visualiando e Empilhando
* Reshaping - Muda o shape de um tensor
* View - Retorna uma visaualização do tensor mantendo o mesmo espaço na memória
* Stacking - Combina tensores emcima ou ao lado de outro tensor
* Squeeze - Usqueeze - remove todas as dimensões com 1 de um tensor
Adiciona uma dimensão de 1 a um tensor
* Permute - Retorna uma View, mas com dimenões alteradas

In [154]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [156]:
x_reshaped = x.reshape(1,9) #Adiciona uma dimensão 
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [157]:
x_reshaped = x.reshape(9,1) #Adiciona uma na outra dimensão
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [158]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [162]:
z = x.view(1,9)
z, z.shape # Mudando z, muda x, pois eles compartilham do mesmo espaço na memória

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [176]:
z = x
x_stacked = torch.stack([x,z], dim=0)
x_stacked


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

Squeezing e Permute

In [183]:
print(x.shape)
print(x.unsqueeze(dim=0)) # dim=1 ele adiciona uma dimensão nas colunas
print(x.squeeze(dim=0)) # Remove dimensões singulares (1)


torch.Size([9])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [193]:
tensor = torch.rand(224,224,3)
tensor.shape, torch.permute(tensor, [2,0,1]).shape #Muda a ordem das dimensoes 

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Indexando